name: A workflow to build books using Enki
on: push
jobs:
  build:
    name: Build book
    runs-on: ubuntu-latest
    container: samuelklutse/enki_epub:latest
    permissions:
      deployments: write
      packages: write
      contents: write
    steps:
      - name: Set Tag as and Env variable
        run: echo "TAG=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
      - name: Build Book
        run: |
          echo 'Initializing Book Build'
          cd /github
          git clone https://github.com/openstax/enki
          cd enki
          git checkout epub 
          TRACE_ON=1 /github/enki/dockerfiles/enki-in-container --command all-git-epub --repo-dir ${{ github.workspace }} --style=dummy
          ls -alt /tmp
